### ISSUE TITLE
JDK版本过高

### ISSUE THREAD

**Issue by lazzman** [lqs1848/AllatoriCrack#1]
Java8无法使用，crack版使用的jdk14

**Comment by lqs1848** [comment]
你直接使用我生成的吗?
你自己生成试一下
我用的jdk14
allatori 并没有要求 jdk14 只是 支持14而已

`Version 7.4 - June 01, 2020
- Java 14 support
- obfuscation warnings from console output are also put in the log file`

**Comment by GXSZone** [comment]
使用原版就可以，破解版就报错

`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/lqs1848/crack/allatori/RandomName has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.allatori.iIiIiiIIII.THIS_IS_DEMO_VERSION_NOT_FOR_COMMERCIAL_USE(pk)
	at com.allatori.IiiIIIiiiI.THIS_IS_DEMO_VERSION_NOT_FOR_COMMERCIAL_USE(wr:239)
	at com.allatori.Obfuscate.main(pv:313)`

**Comment by zxy1994** [comment]
> 用的Java8
我拉了代码，用java8生成了一个，见附件。作者源码的seedList用了List.of，java8没这方法。
[java8Versioncrack.zip](https://github.com/user-attachments/files/15789333/java8Versioncrack.zip)
